<script type="text/javascript">
$(document).ready(function(){
	$(".btnObrisi").click(function(){
		var id=$(this).attr('idStavka');
		$("#dlgBrisanje").data({"idStavka":id}).dialog('open');
		});
	$("#dlgBrisanje").dialog({autoOpen: false, 
		modal: true,
		width: 500,
		show: {
	        effect: "blind",
	        duration: 200
	      },
	      hide: {
	        effect: "explode",
	        duration: 200
	      },
		buttons: [{
			text:"Проследи",
			class : 'btn btn-success',
			click: function() {
				var id=$(this).data("idStavka");
			    $( this ).dialog('close');
				$.ajax({
					type	:	"POST",
					cache	: 	false,
					url		:	"/ajax/obrisi-stavku-racuna",
					data	: 	{idStavka:id},
					success	: function(data){
						$('#divTabela').html(data);
					}
						
				});
	    	}},
	    	{text:"Откажи",
	    		class : 'btn btn-danger',
	        	click: function() {
	        	$( this ).dialog( "close" );
	    	}}]});
	$("#btnDodaj").click(function(){
		$("#dlgStavke").load("/dijalog/dlg-stavke/idRacun/<?php echo $this->idRacun;?>/kurs/<?php echo $this->kurs;?>;?>", function(){
			$("#dlgStavke").dialog('open');
		});
	});
		$("#dlgStavke").dialog({autoOpen: false, 
			modal: true,
			width: 500,
			show: {
		        effect: "blind",
		        duration: 200
		      },
		      hide: {
		        effect: "explode",
		        duration: 300
		      },
			buttons: [{
				text:"Проследи",
				class : 'btn btn-success',
				click: function() {
					if( $("#frmStavke").validationEngine('validate') ) {
				    $( this ).dialog('close');
					$.ajax({
						type	:	"POST",
						cache	: 	false,
						url		:	"/ajax/dodaj-stavku-racunu",
						data	: 	$("#frmStavke").serialize(),
						success	: function(data){
							$("#divTabela").html(data);
						}
							
					});
					}
		    	}},
		    	{text:"Откажи",
		    		class : 'btn btn-danger',
		        	click: function() {
		        	$( this ).dialog( "close" );
		    	}}]});
});
</script>
<div class="block-fluid" >
<div id="divTabela">
	<table class="table" width="100%" cellspacing="0" cellpadding="0" >
		<thead>
			<tr>
				<th style="width: 10px">Шифра</th>
				<th>Назив добара</th>
				<th>Ј.М.</th>
				<th>Количина</th>
				<th>Јед.цена</th>
				<th>Износ у динарима</th>
				<th>Пор.основица</th>
				<th>Ст.пдв</th>
				<th>Износ пдв</th>
				<th>Укупна накнада</th>
				<th> </th>
			</tr>
		</thead>
		<tbody>
		<?php $pom = 0; foreach ($this->stavke as $s):?>
		      <?php 
		      if($this->pdv!=1) { $pom += $s['ukupno']; } 
				else {$pom += $s['ukupno_sa_pdv'];}
		      ?>
		      
		      
			<tr>
				<td style="width: 10px"><?php echo $s['sifra'];?></td>
				<td><?php echo $s['na_ime']?></td>
				<td>ком</td>
				<td><?php echo $s['kolicina']?></td>
				<td><?php echo number_format($s['cena_jm'],2,',','.')." ".$s['valuta']?></td>
				<td><?php echo number_format($s['ukupno'],2,',','.')?></td>
				<td><?php echo number_format($s['ukupno'],2,',','.')?></td>
				<td><?php if ($this->pdv!=1){?>0%<?php } else { echo $s['pdv'].'%'; }?></td>
				<td><?php if ($this->pdv!=1){ echo '0.00';} else{ echo number_format($s['ukupno_sa_pdv']-$s['ukupno'],2,',','.');}?></td>
				<td><?php if ($this->pdv!=1){echo number_format($s['ukupno'],2,',','.');} else{ echo number_format($s['ukupno_sa_pdv'],2,',','.');}?></td>
				<td style="text-align: center; width: 30px">
					<a><button class="btn btn-sm btn-danger tip btnObrisi" idStavka="<?php echo $s['id']?>" data-original-title="Обриши"><i class="glyphicon glyphicon-trash"></i></button></a>
				</td>
			</tr>
			<?php endforeach;?>
			<tr>
				<td colspan="9" style="text-align: right;">Укупно:</td>
				<td><?php echo number_format($pom,2,",",".")?></td>
				<td></td>
			</tr>
		</tbody>
	</table>
	</div>
	<form action='/racun/unos-racuna/noviRacun/1'>
	<div class="row-form clearfix footer tal" style="border-top: none;">
		<input type='hidden' name='datumR' value='<?php echo $this->datumR;?>'>
		<input type='hidden' name='datumD' value='<?php echo $this->datumD;?>'>
		<input type='hidden' name='datumV' value='<?php echo $this->datumV;?>'>
		<input type='hidden' name='datumK' value='<?php echo $this->datumK;?>'>
		<input type='hidden' name='kurs' value='<?php echo $this->kurs;?>'>
		<button class="btn btn-warning tip btnNovi" data-original-title="Novi Racun" type="submit" >Нови рачун</button>
		<a href="/stampa/racun/idRacun/<?php echo $this->idRacun;?>">
		<button class="btn btn-success tip" data-original-title="Stampaj" type="button" >Штампај</button></a>
		<button class="btn btn-info tip " id="btnDodaj" data-original-title="Dodaj" type="button" >Додај</button>			
	</div>
	</form>
</div>


<div class="dialog" id="dlgStavke" title="Додавање услуга"></div>
<div class="dialog" id="dlgBrisanje" title="Потврда">Да ли сте сигурни
	да желите да обришете услугу?</div>